### ISSUE TITLE
An example

### ISSUE THREAD

**Issue by GSoria3D** [TatjanaKutzner/CityGML-UtilityNetwork-ADE#1]
Hi! I'm working about Utility Network ADE. I need to export my database to a CityGML file. Can you upload some example of a complete network please? Thanks!

**Comment by TatjanaKutzner** [comment]
Thanks a lot for your interest in the Utility Network ADE. 
We are currently in the process of preparing publicly available test data sets, however, it will still take a few weeks until they are ready. For more information on the current state of development see here: http://en.wiki.utilitynetworks.sig3d.org/index.php/2017_VI_Agenda_of_the_Workshop. 
As soon as they are ready, we will provide them here on github.

**Comment by TatjanaKutzner** [comment]
I am pleased to announce that our first test data set is now available. It's accessible in the folder Sample/Nanaimo_Water_Network together with the source data and the FME workspace developed for transforming the source data to CityGML. The data set represents a water network from the City of Nanaimo in Canada and provides a good example for how networks are to be structured in a CityGML file. We plan to enrich the data set with further network components and other city objects such as buildings within the next weeks, but the data set can already perfectly be used as it is.
