### ISSUE TITLE
Latest Schema may not be valid (?)

### ISSUE THREAD

**Issue by PRemmen** [TatjanaKutzner/CityGML-UtilityNetwork-ADE#9]
I was trying to import your UtilityNetwork-ADE into 3D City Database with the new ADE Plugin. However, this failed. 

After passing your XSD Schema to Altova XML Spy I was getting following error:

![grafik](https://user-images.githubusercontent.com/8124013/54274855-7eb2e480-4589-11e9-9678-5953bfad04ef.png)

I commented line 187 in the schema and at least the 3D City DB ADE Plugin worked with the updated schema, and I was getting no more errors in Altova.

```xml
<element minOccurs="0" name="connectedCityObject" type="core:_CityObjectPropertyByValueType"/>
```

I'm not an expert for GML or XSD so I don't now if this is really an error in the schema or if I'm missing something else here. Any help highly appreciated :) @TatjanaKutzner @iboates

**Comment by TatjanaKutzner** [comment]
Thanks a lot for your feedback. 
Yes, it's an error. The ShapeChange configuration file was missing an entry on the property type the class _CityObject should be mapped to which resulted in an incorrect type in the xsd.
I uploaded a new xsd file, commit bedbcf61525a883da611dab84b34c2b8b2afcb0b.

**Comment by TatjanaKutzner** [comment]
The mapping to the type `core:AbstractCityObjectType` in the ShapeChange configuration file is still not correct. The mapping needs to be changed to `gml:ReferenceType`. Only in this way it is possible to reference city objects in the following way in instance documents: 
```xml
<utility:connectedCityObject xlink:href = “#CityObjectID"/>
```
`gml:ReferenceType` is also used in the Energy ADE for referencing city objects.
